version: "3.7"
services:
    react-vite:
        tty: true
        stdin_open: true
        build: .
        # restart: always
        ports:
            - "5173:5173"
        volumes:
            # dont create reference for folder node_modules
            # - "/app/node_modules"
            - "./src:/app/src"
