version: "3.7"
services:
    react-docker-boilerplate:
        tty: true
        stdin_open: true
        build: .
        # restart: always
        ports:
            - "3000:3000"
        volumes:
            # dont create reference for folder node_modules
            # - "/app/node_modules"
            - "./src:/app/src"
